apiVersion: 1

datasources:
  - name: Telemetry Postgres
    type: grafana-postgresql-datasource
    uid: telemetry-postgres
    access: proxy
    url: localhost:5432
    database: telemetry
    user: telemetry_user
    secureJsonData:
      password: ${DB_PASS}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1400  # Postgres 14+
      timescaledb: false
    isDefault: true
    editable: true
